name: flask_env
channels:
  - conda-forge
  - defaults
dependencies:
  - alembic=1.9.4
  - blas=1.0
  - bottleneck=1.3.5
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - cffi=1.15.1
  - click=8.0.4
  - cryptography=38.0.4
  - dash=2.7.0
  - dnspython=2.2.1
  - email-validator=1.2.1
  - flask=2.2.2
  - flask-compress=1.13
  - flask-login=0.6.2
  - flask-migrate=4.0.4
  - flask-sqlalchemy=3.0.2
  - flask-wtf=1.0.1
  - greenlet=2.0.1
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib_resources=5.12.0
  - intel-openmp=2021.4.0
  - itsdangerous=2.0.1
  - jinja2=3.1.2
  - libcxx=14.0.6
  - libffi=3.4.2
  - mako=1.2.4
  - markupsafe=2.1.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.4
  - numexpr=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openssl=1.1.1t
  - packaging=22.0
  - pandas=1.5.2
  - pip=22.3.1
  - plotly=5.9.0
  - pycparser=2.21
  - python=3.10.9
  - python-dateutil=2.8.2
  - pytz=2022.7
  - readline=8.2
  - setuptools=65.6.3
  - six=1.16.0
  - sqlalchemy=1.4.39
  - sqlite=3.40.1
  - tenacity=8.0.1
  - tk=8.6.12
  - tzdata=2022g
  - werkzeug=2.2.2
  - wheel=0.38.4
  - wtforms=2.3.3
  - xz=5.2.10
  - zipp=3.14.0
  - zlib=1.2.13
